### ISSUE TITLE
getMeasurements does not work with background measurements

### ISSUE THREAD

**Issue by atsanda** [MagneticParticleImaging/MPIFiles.jl#101]
I am trying to load an mdf which contains background measurements only using
```julia
c = getMeasurements(c_mdf, false; tfCorrection=false, spectralLeakageCorrection=false)
```
I get the following error:
```
ERROR: BoundsError: attempt to access 3300000-element Vector{Bool} at index [3300001]
Stacktrace:
 [1] getindex
   @ ./essentials.jl:13 [inlined]
 [2] measBGFrameIdx(f::MDFFileV2{Array{Int16, 4}})
   @ MPIFiles ~/.julia/packages/MPIFiles/Ag3SE/src/Derived.jl:52
 [3] top-level scope
   @ /.../Main.jl:5
```
I think it is caused by `measBGFrameIdx`

**Comment by jusack** [comment]
While I was changing stuff in Derived.jl I removed the manual implementation of `measBGFrameIdx` and just used Julia's `findall`. If you could check if this fixes your issue that would be great :)

**Comment by nHackel** [comment]
@atsanda and @jusack, I tested your branch Justin and it works with the mdf in question. So when we merge #107 we can close this issue
