### ISSUE TITLE
CI: Make Breakage checks optional

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIFiles.jl#102]
Depends on https://github.com/orgs/community/discussions/15452

**Comment by nHackel** [comment]
Getting things to properly work with the comment wasn't really working out. Instead I made it so that breakage tests are only run on a PR if the request is labelled with `breakage`. And labeling a PR with that label also triggers the run (and shouldn't retrigger the normal CI)

**Comment by nHackel** [comment]
It looks like this if the label is missing:
![image](https://github.com/user-attachments/assets/5d8d977a-aeac-44a5-8711-32d51ef2a5ff)
