### ISSUE TITLE
rxFrequencies produces wrong result

### ISSUE THREAD

**Issue by jusack** [MagneticParticleImaging/MPIFiles.jl#105]
I just noticed that there seems to be a bug in the calculation of rxFrequencies, see the following MWE.
I would expect the first frequency to be exactly 25kHz as it is the case with the rfftfreq function, the MPIFiles function wrongly gives 25.04006... kHz. 
I think the problem is the uneven number of rxNumSamplingPoints, with e.g. 1000 (15.625 kHz base frequency) the two functions match.

```julia
using MPIFiles, MPIFiles.FFTW
f = MDFv2InMemory(Dict{Symbol,Any}(:rxNumSamplingPoints=>625, :rxBandwidth=>125e6/8/2))

f1 = rxFrequencies(f) # 313 steps of 25.04006... kHz until 7.8125 MHz
f2 = rfftfreq(rxNumSamplingPoints(f), 2*rxBandwidth(f)) # 313 steps of 25 kHz until 7.8 MHz

f1[2] == f2[2] # false
```

We could just move to using the rfftfreq function with collect directly in rxFrequencies

**Comment by jonschumacher** [comment]
This also relates to #98. In the case of frequency filtered data, the function should return the selection of frequencies.
