### ISSUE TITLE
Julia 1.11 breaks UniformRandomPositions test

### ISSUE THREAD

**Issue by jusack** [MagneticParticleImaging/MPIFiles.jl#108]
Apparently there have been some changes in the RNG code in Julia 1.11 causing the tests on UniformRandomPositions to fail.
Is is important that the random positions are always identical even between julia versions? If yes, we should probably move to using StableRNGs which had an update working around the change in Julia 1.11 (https://github.com/JuliaRandom/StableRNGs.jl/issues/20) 
However, this will lead to a breaking change for the older Julia versions as the RNG will be different

**Comment by tknopp** [comment]
Yes the solution is to switch to StableRNG, which then will also work for older Julia versions. I would not consider that to be a breaking change. I mean: Julia seems to also not consider that to be a breaking change ;-)
