### ISSUE TITLE
str2uuid

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MPIFiles.jl#17]
Why do we have the `str2uuid` function in `Utils.jl`?

**Comment by tknopp** [comment]
It was used, when trying to convert the Bruker UID into a UUID. You switched that to using the UID being the seed for the UUID. So in other words: It can be removed.

The try / catch thing was a workaround for corrupt files. It might be good going through all our files an checking if the UUIDs are correct (i.e. UUID(str) does not give an error).

**Comment by hofmannmartin** [comment]
I will do so
