### ISSUE TITLE
bug in calculation of measFramePermutation for Bruker system matrix

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MPIFiles.jl#7]
Reading a very simple system matrix indicated that `measFramePermutation` is not calculated correctly if a Bruker System matrix is loaded.

It should have been 2,3,4,...,67,1,68 but was 1,2,...,68

**Comment by tknopp** [comment]
yes this is a bug.

**Comment by tknopp** [comment]
I have a fix
